---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: Europe/Istanbul
lsi: false
markdown: kramdown


### content configuration ###
title:       "Uçkan Bilim Köyü"
keywords:    "bilim köyü, ekolojik köy, otonomi, özgür Uçkan"
description: "Uçkan Bilim Köyü Projesi sayfasıdır"
source_link: "https://github.com/alirizakeles/bilimkoyu"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  sapphire: '#2779A6'
  purpleray: '#AEA7CF'
  petal: '#E5B3D0'
  pebble: '#2F4844C'

kramdown:
  auto_ids:  false
